### PR TITLE
add PHP 7.4 images

### PR DESCRIPTION
**Pull request by vdloo**

### CODE REVIEW

**Comment by SanderRoosingh** [comment]
No php 7.4, mysql 8.0 combination?

**Comment by vdloo** [comment]
we can but the docker repo doesn't like it, the image happens to get too big. we need to find out how to remove this restriction from the docker repo:
```
172.17.0.2                 : ok=392  changed=313  unreachable=0    failed=0    skipped=348  rescued=0    ignored=0
2020-07-21 07:19:23,060 INFO [172.17@unregistered] hypernode.jobs.taskflow_tasks.provisioning: Completed update of unregistered - 172.17.0.2 (magweb-docker)
The push refers to repository [docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql80]
a9a3ef90a9c4: Preparing
6059d384729e: Preparing
62dec665d8ed: Preparing
92f1092b6c31: Preparing
a62ad6b0c52d: Preparing
5d736577766c: Preparing
2df5cbb11b4e: Preparing
dc77a3de5e14: Preparing
559a9092aea6: Preparing
5065100e0ff6: Preparing
58946b3545dd: Preparing
1c76bd0dc325: Preparing
559a9092aea6: Waiting
5065100e0ff6: Waiting
58946b3545dd: Waiting
5d736577766c: Waiting
1c76bd0dc325: Waiting
2df5cbb11b4e: Waiting
62dec665d8ed: Pushed
92f1092b6c31: Pushed
a62ad6b0c52d: Pushed
6059d384729e: Pushed
559a9092aea6: Mounted from byteinternet/hypernode-buster-docker
5065100e0ff6: Mounted from byteinternet/hypernode-buster-docker
5d736577766c: Pushed
58946b3545dd: Mounted from byteinternet/hypernode-buster-docker
2df5cbb11b4e: Pushed
1c76bd0dc325: Mounted from byteinternet/hypernode-buster-docker
dc77a3de5e14: Pushed
error parsing HTTP 413 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n"
fcf64b52d24fb0d58ffbdf5b25fd21598c98cba31dc52b8ff2fc20be9b28c38e
Fatal error: local() encountered an error (return code 1) while executing 'docker push docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql80:latest'
```
it's in saltyparrot

**Comment by SanderRoosingh** [comment]
Ahja, that is annoying. For now this is fine then.

**Comment by vdloo** [comment]
probably just an nginx config thing

**Pull request merged**
